### PR TITLE
Replace GitVersion with a custom, ad hoc solution for version management

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Review by thomaslevesque — APPROVED** [review]
If I read this correctly, this means that manual builds will always be `x.y.z-adhoc+Build.adhoc-Sha.adhoc`, and only AppVeyor builds where the tag matches the version from the release notes will be `x.y.z`. Right?

This seems to be a good approach 👍

**Comment by thomaslevesque** [comment]
I think I might have missed something. The package filename in the artifacts is not what I expected. Shouldn't it be `SelfInitializingFakes.0.1.0-adhoc+Build.32-Sha.39e8f1541660a628d51b6833957fab81ee27d271.nupkg`? Or is `nuget pack` supposed to drop the part after the `+`?

**Comment by blairconrad** [comment]
I wondered about that as well, @thomaslevesque. I think `nuget pack` is dropping the part after the `+`. 
I should experiment.,

**Comment by blairconrad** [comment]
Yeah, that's what `nuget pack` does. Unexpected, but I'm not against it…

**Pull request merged**
