### PR TITLE
[WIP] test switching from build.ps1 to build.cmd to solve #60

### PR DESCRIPTION
**Pull request by adamralph**
Connects to #60.

### CODE REVIEW

**Comment by adamralph** [comment]
The build fails, and is reported as failure: https://ci.appveyor.com/project/blairconrad/selfinitializingfakes/build/85-gclbjcbi

@blairconrad it looks like the use of `build.ps1` rather than `build.cmd` is problematic.

**Review by blairconrad — CHANGES_REQUESTED** [review]
Thanks, @adamralph. It'd be nice to stick with a ps1, but that seems fraught, and I don't mind so much switching to cmd. I'd ask that you remove the bad package and update the how_to_build and we're off to the races.

**Comment by adamralph** [comment]
@blairconrad before doing that, I'd like understand what is wrong with using `build.ps1` and whether there is a way to fix it. Reason being, I provide a sample `build.ps1` in Bullseye, and I know of at least one other project which uses it.

**Comment by adamralph** [comment]
@blairconrad I've raised #65 to fix #60, and I've raised https://github.com/adamralph/bullseye/issues/83 to look into the ps1 problem.

**Pull request closed without merging**
