### PR TITLE
Update NuGet API key

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Review by thomaslevesque — APPROVED** [review]
Thanks @blairconrad. Did you renew the key on NuGet?

**Comment by blairconrad** [comment]
> Did you renew the key on NuGet?

I did renew it on NuGet. Is that not the way to go anymore?

**Comment by thomaslevesque** [comment]
> I did renew it on NuGet. Is that not the way to go anymore?

Yes, I was just wondering why

**Comment by blairconrad** [comment]
NuGet was nice enough to e-mail me that the key is expiring in 5 days or whatever. It usually does, IIRC.

OH! Do you think this is the FakeItEasy repo?

**Comment by thomaslevesque** [comment]
> OH! Do you think this is the FakeItEasy repo?

Actually, I did! oops...

**Pull request merged**
