### PR TITLE
[WIP] reproduce #60

### PR DESCRIPTION
**Pull request by adamralph**
Connects to #60

### CODE REVIEW

**Comment by adamralph** [comment]
The build is failing, but is being reported as success, as predicted: https://ci.appveyor.com/project/blairconrad/selfinitializingfakes/build/85-ehgueeyd

**Review by blairconrad — COMMENTED** [review]
Thanks for your interest, @adamralph, but I must confess that I do not see the value in this change, other than  as durable proof that a failed build is not detected properly.

In general, I prefer builds to pass, so am reluctant to merge this.

**Comment by adamralph** [comment]
Sorry for not making myself clear @blairconrad. This is not meant to be merged. It's just meant to reproduce the problem described in #60.

**Comment by blairconrad** [comment]
> Sorry for not making myself clear @blairconrad. This is not meant to be merged. It's just meant to reproduce the problem described in #60.

Yeah, I was having some fun. Sorry I didn't make that apparent. I understood your intent, but thought the approach was odd, so I was, if I may try something that I think is from your vernacular, "taking the Mickey". 😜

**Comment by adamralph** [comment]
#60 is fixed by #65

**Pull request closed without merging**
