### PR TITLE
upgrade to Bullseye 1.2.0-rc.2

### PR DESCRIPTION
**Pull request by adamralph**
- [Attempt to automatically enable console colors in Windows](https://github.com/adamralph/bullseye/issues/73)
- [Source stepping](https://github.com/adamralph/bullseye/issues/52)

### CODE REVIEW

**Comment by adamralph** [comment]
Marking as WIP until the new package is available for restore (the build is actually failing, see #60).

**Comment by adamralph** [comment]
The build is succeeding now.

**Review by blairconrad — APPROVED** [review]
Thanks, @adamralph. I work under Powershell in ConEmu, so didn't even know there was a problem with colours on Windows.

**Comment by adamralph** [comment]
Me too, but recently some people have started to wonder why they get weird output in cmd.exe. MS added ANSI colour processing to the console in Windows 10, but unfortunately they decided to disable it by default. I guess there were some backwards compatibility edge cases they were worried about.

**Comment by blairconrad** [comment]
Thanks, @adamralph. This change was "released" in 0.4.0.
Check for your name in the [release notes](https://github.com/blairconrad/SelfInitializingFakes/releases/tag/0.4.0)! 🎯

**Pull request merged**
